### ISSUE TITLE
typescript error using library

### ISSUE THREAD

**Issue by petertellgren** [GuptaSiddhant/react-broadcast-channel#1]
Hi, firs of all thanks for writing a fantastic lib. 

When importing the lib I keep getting the following typescript error:

```
Could not find a declaration file for module 'use-broadcast-channel'. '.../node_modules/use-broadcast-channel/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/use-broadcast-channel` if it exists or add a new declaration (.d.ts) file containing `declare module 'use-broadcast-channel';`ts(7016)
```
I saw in the build script that there is a `tsc` command to generate a `d.ts` but I'm unable to find it in the `./dist` folder. 

I think the issue is that the file is indeed generated but output to `./dist/src/index.d.ts` and thereby not resolved.

manually moving the file worked for me so I guess it's a minor tweak to the `tsconfig.json` file needed.

Will try to fix and submit a PR

**Comment by petertellgren** [comment]
PR opened: https://github.com/GuptaSiddhant/react-broadcast-channel/pull/2

**Comment by petertellgren** [comment]
tried to fix this in PR (now closed) but ran in to other issue: 
- dynamic react import error

**Comment by 7coil** [comment]
I've temporarily patched `package.json` with...

```
  "types": "./dist/src/index.d.ts",
```
